# Generated by Django 5.2.11 on 2026-03-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('momo', 'Mobile Money'), ('bank', 'Bank Transfer')], max_length=20),
        ),
    ]
