# Generated by Django 6.0.2 on 2026-03-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_role_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
